services:
  # The AI Backend Gateway
  - type: web
    name: aship-api-gateway
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_gateway.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  # The Analytics Flask App
  - type: web
    name: aship-demo-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn demo_app.app:app -w 4 -k gevent --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
