apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-config-err
  namespace: demo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: aship/auth:v999.NON_EXISTENT # Typo causing ImagePullBackOff
        ports:
        - containerPort: 8080
